import type { NextConfig } from "next";

const nextConfig: NextConfig = {
    /* config options here */
    // Emit a self-contained server bundle for Docker / Helm self-hosting.
    // The OpenNext (Cloudflare) build path ignores this and continues to
    // work because it consumes `.next/` directly.
    output: "standalone",
    reactCompiler: true,
    // When the local dev server is exposed via a Cloudflare tunnel for
    // remote testing (legal.dashable.dev), Next blocks HMR + RSC fetches
    // from that origin by default — the page never finishes hydrating.
    // Whitelist the tunneled host so dev works end-to-end through the
    // public URL.
    allowedDevOrigins: ["legal.dashable.dev", "legal-api.dashable.dev"],
    // `/sitemap.xml` and `/robots.txt` are now generated by `src/app/sitemap.ts`
    // and `src/app/robots.ts` — no rewrite needed (the old rewrite pointed at
    // an `/api/sitemap` route that never existed).
    // Billing was removed (decision #7) — Louis is 100% free, BYO API key.
    // Keep saved links working by routing them at the edge instead of
    // hosting placeholder pages that flash before redirecting.
    async redirects() {
        return [
            { source: "/billing", destination: "/settings/api-keys", permanent: true },
            { source: "/upgrade", destination: "/settings/api-keys", permanent: true },
            // /docs and /help merged into /academy. Serve a real 308 at the
            // edge instead of a client-side router.replace() — crawlers
            // follow it cleanly and link equity flows to /academy.
            { source: "/docs", destination: "/academy", permanent: true },
            { source: "/help", destination: "/academy", permanent: true },
        ];
    },
    skipTrailingSlashRedirect: true,
};

export default nextConfig;
