/**
 * Registry generator: scans the skills directory and produces:
 *   - _REGISTRY.json (machine-readable)
 *   - _REGISTRY.md   (human-readable)
 *
 * Usage: tsx backend/src/skills/_build-registry.ts
 */
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, basename } from "path";

const SKILLS_DIR = __dirname;

interface Entry {
  id: string;
  name: string;
  category: string;
  priority: string;
  status: string;
  intent?: string[];
  practice_area?: string;
  jurisdictions?: string[];
  filename: string;
}

function parseFm(raw: string): Record<string, unknown> {
  if (!raw.startsWith("---")) return {};
  const end = raw.indexOf("\n---", 3);
  if (end < 0) return {};
  const fm: Record<string, unknown> = {};
  for (const line of raw.slice(3, end).trim().split("\n")) {
    const m = /^([\w\-]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const k = m[1], v = m[2];
    if (v.startsWith("[") && v.endsWith("]")) {
      fm[k] = v.slice(1, -1).split(",").map(s => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
    } else {
      fm[k] = v.replace(/^["']|["']$/g, "");
    }
  }
  return fm;
}

const entries: Entry[] = [];
for (const f of readdirSync(SKILLS_DIR)) {
  if (!f.endsWith(".md") || f.startsWith("_")) continue;
  const raw = readFileSync(join(SKILLS_DIR, f), "utf-8");
  const fm = parseFm(raw);
  entries.push({
    id: (fm.id as string) ?? basename(f, ".md"),
    name: (fm.name as string) ?? basename(f, ".md"),
    category: (fm.category as string) ?? "uncategorized",
    priority: (fm.priority as string) ?? "P3",
    status: (fm.status as string) ?? "stub",
    intent: fm.intent as string[] | undefined,
    practice_area: fm.practice_area as string | undefined,
    jurisdictions: fm.jurisdictions as string[] | undefined,
    filename: f,
  });
}

entries.sort((a, b) => a.id.localeCompare(b.id));

writeFileSync(join(SKILLS_DIR, "_REGISTRY.json"), JSON.stringify({ generated_at: new Date().toISOString(), total: entries.length, entries }, null, 2));

// Build markdown
const byCat = new Map<string, Entry[]>();
for (const e of entries) {
  if (!byCat.has(e.category)) byCat.set(e.category, []);
  byCat.get(e.category)!.push(e);
}

const statusEmoji: Record<string, string> = { shipped: "✅", reviewed: "🟢", drafted: "🟡", stub: "⚪" };
const priorityEmoji: Record<string, string> = { P0: "🔴", P1: "🟠", P2: "🟡", P3: "⚪" };

let md = `# Louis Skills Registry\n\n`;
md += `_Auto-generated by \`_build-registry.ts\`. Do not edit by hand._\n\n`;
md += `**Total skills:** ${entries.length}\n\n`;
md += `**Status counts:**\n`;
const statusCounts: Record<string, number> = {};
for (const e of entries) statusCounts[e.status] = (statusCounts[e.status] ?? 0) + 1;
for (const [s, n] of Object.entries(statusCounts)) {
  md += `- ${statusEmoji[s] ?? "?"} **${s}**: ${n}\n`;
}
md += `\n## Legend\n\n`;
md += `Status: ${statusEmoji.shipped} shipped · ${statusEmoji.reviewed} reviewed · ${statusEmoji.drafted} drafted · ${statusEmoji.stub} stub\n\n`;
md += `Priority: ${priorityEmoji.P0} P0 (critical path) · ${priorityEmoji.P1} P1 · ${priorityEmoji.P2} P2 · ${priorityEmoji.P3} P3 (nice-to-have)\n\n`;
md += `---\n\n`;

const catNames: Record<string, string> = {
  "router": "A. Router & meta layer",
  "conversation": "B. Conversation & UX",
  "draft": "C. Drafting",
  "review": "D. Review / redline / risk",
  "research": "E. Research",
  "tool": "F. Tool-calling integrations",
  "output": "G. Citations / sources / output formatting",
  "kb": "H. Practice-area knowledge packs",
  "persona": "I. Persona / role layer",
  "efirm": "J. eFirm specific",
  "public-tool": "K. Free public tools",
  "eval": "L. Evaluation / judging",
  "safety": "M. Safety / compliance / refusal",
  "onboarding": "N. Onboarding / activation",
  "growth": "O. Growth / lifecycle",
  "ops": "P. Ops / admin",
  "voice": "Q. Voice / multimodal",
  "workflow": "R. Workflow / agent",
  "heuristic": "S. Cross-cutting heuristics",
  "justice": "T. Justice product-demo",
  "docs": "U. Documentation surfaces",
  "academy": "V. Academy / learning",
  "blog": "W. Blog as knowledge",
  "site": "X. Site-as-knowledge",
  "unlock": "Y. Capability-unlock",
  "feed": "Z. Feed / changelog",
  "prompt-pack": "K. Prompt-pack templates (152 from HAQQ library)",
};

for (const cat of [...byCat.keys()].sort()) {
  const items = byCat.get(cat)!;
  md += `## ${catNames[cat] ?? cat} (${items.length})\n\n`;
  for (const e of items) {
    md += `- ${statusEmoji[e.status] ?? "?"} ${priorityEmoji[e.priority] ?? "?"} **${e.id}** — ${e.name}`;
    if (e.intent && e.intent.length) md += ` _(intent: ${e.intent.slice(0, 3).join(", ")})_`;
    md += `\n`;
  }
  md += `\n`;
}

writeFileSync(join(SKILLS_DIR, "_REGISTRY.md"), md);
console.log(`registry: total=${entries.length}`);
for (const [s, n] of Object.entries(statusCounts)) {
  console.log(`  ${s}: ${n}`);
}
