{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "louis.serviceAccountName" . }}
    labels:
        {{- include "louis.labels" . | nindent 8 }}
{{- end }}
